### ISSUE TITLE
What liscence am I allowed to use? 

### ISSUE THREAD

**Issue by imadnyc** [tweag/python-nix-flake-template#2]
If I use this template as a launchpad for my own code, can I license it under GPLv3? According to this https://code.whatever.social/exchange/opensource/questions/9110/can-i-ignore-an-open-source-license-if-i-checkout-a-version-that-was-released-pr , I don't have the rights to use this code as long as it doesn't have a license. Is the solution for you to add one? 

Thanks,
Abdullah Imad

**Comment by GuillaumeDesforges** [comment]
Closed in https://github.com/tweag/python-nix-flake-template/commit/610b5b9e6d65844d27919be1be09d854e1ffa2f3
